### PR TITLE
Update to Cmdliner v1.1.0

### PR DESCRIPTION
**Pull request by hra687261**
And remove some warnings

### CODE REVIEW

**Comment by Gbury** [comment]
You need to update the lower bound on cmdliner in the opam file

**Comment by hra687261** [comment]
> curious, is the printbox constraint update something needed to remove warnings?

Not warnings, but to avoid compilation errors. `printbox-text` was moved into it's own package since the 0.6 version of `printbox`. With lower versions, dune complains that there is no `printbox-text` package. With a 0.6 and higher version, the code won't compile without adding  `printbox-text` as a dependancy.

> also: welcome grin wave

Thank you! :smile:

**Comment by c-cube** [comment]
Oh right, that makes sense!! I forgot about the split. Carry on then :)

**Comment by c-cube** [comment]
for the failing test : the output has changed, but if it's just because of the unicode boxes, try:

```
dune runtest --auto-promote
```

and commit the result. The `promote` thing means it'll add the changes back into the source tree.

**Comment by hra687261** [comment]
You're welcome! :grin:

**Pull request merged**
